apiVersion: v1
kind: Service
metadata:
  name: vote
spec:
  selector:
    app: vote
  ports:
    - name: vote-prod
      port: 8081
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: result
spec:
  type: LoadBalancer
  selector:
    app: result
  ports:
    - name: result-prod
      port: 8080
      targetPort: 4000