- name: Set fixed timestamp
  set_fact:
    fixed_timestamp: "{{ lookup('pipe', 'date +%Y-%m-%d_%H-%M-%S') }}"
  run_once: true
  delegate_to: localhost

- name: Set backup filename
  set_fact:
    backup_filename: "postgres_backup_{{ fixed_timestamp }}.sql"

- name: Ensure local backup directory exists
  file:
    path: "{{ local_backup_dir }}"
    state: directory
    mode: '0755'
  delegate_to: localhost
  become: no

- name: Dump database from primary
  shell: |
    PGPASSWORD="{{ pg_password }}" pg_dump -U "{{ pg_username }}" -h localhost postgres
  register: pg_dump_output
  become_user: postgres
  when: inventory_hostname == groups['all'][0]
  no_log: true

- name: Copy dump to controller
  copy:
    content: "{{ pg_dump_output.stdout }}"
    dest: "{{ local_backup_dir }}/{{ backup_filename }}"
    mode: '0644'
  delegate_to: localhost
  when: inventory_hostname == groups['all'][0]
  become: no